### PR TITLE
fix: correct WebSocket authentication callback

### LINKED ISSUE #532: WebSocket API key authentication fails with HTTP 500 due to incorrect `process_request` callback
## Summary

WebSocket API key authentication introduced in #449 is currently broken. When the server is started with `--api_key`, WebSocket handshakes fail with HTTP 500 even when clients provide valid credentials.

Both supported authentication methods are affected:

- `Authorization: Bearer <key>`
- `?token=<key>`

## Verified against

- WhisperLive `main` at commit [`8e68b5e`](https://github.com/collabora/WhisperLive/commit/8e68b5ef60d695df00ed663b9eb034b28965a189)
- `websockets` 16.1

## Steps to reproduce

1. Start the server with an API key:

   ```bash
   python run_server.py --api_key test-key
   ```

2. Attempt an authenticated connection using either method:

   ```python
   from websockets.sync.client import connect

   # Query parameter
   connect("ws://localhost:9090/?token=test-key")

   # Or Authorization header
   connect(
       "ws://localhost:9090/",
       additional_headers={"Authorization": "Bearer test-key"},
   )
   ```

## Actual behavior

The handshake fails with HTTP 500, and the server logs:

```text
AttributeError: 'Request' object has no attribute 'get'
```

## Expected behavior

- Valid Bearer tokens and `?token=` values should complete the WebSocket upgrade.
- Invalid or missing credentials should receive HTTP 401.

## Cause

`websockets.sync.server.serve` calls `process_request` with:

```python
(connection, request)
```

However, `_ws_auth` currently treats these arguments as:

```python
(path, request_headers)
```

Consequently, it calls `.get()` directly on the `Request` object instead of using `request.headers`, and it attempts to parse the connection object as the request path.

There is also a second API mismatch: the sync API expects `process_request` to return a `websockets.http11.Response` or `None`, while `_ws_auth` currently returns a legacy `(status, headers, body)` tuple for rejected requests.

The documented callback type is:

```python
Callable[[ServerConnection, Request], Response | None]
```

## Suggested fix

Read the path and headers from `request.path` and `request.headers`, and return a proper response, possibly through `connection.respond(HTTPStatus.UNAUTHORIZED, "Unauthorized\n")`.

It would also be helpful to add handshake-level tests that start a real server with the production callback and verify:

- A valid Bearer token succeeds.
- A valid query-string token succeeds.
- Invalid or missing credentials return HTTP 401 rather than HTTP 500.

The five existing WebSocket authentication tests added in #449 duplicate `_ws_auth` and invoke the copy directly with a string path and a plain dictionary. They don't exercise the production callback or perform a real WebSocket handshake, so they don't catch either API mismatch.

## References

- Feature introduction: https://github.com/collabora/WhisperLive/pull/449
- Affected implementation: https://github.com/collabora/WhisperLive/blob/8e68b5ef60d695df00ed663b9eb034b28965a189/whisper_live/server.py#L855-L869
- Existing tests: https://github.com/collabora/WhisperLive/blob/8e68b5ef60d695df00ed663b9eb034b28965a189/tests/test_server_extended.py#L656-L696
- Original report: https://github.com/collabora/WhisperLive/pull/449#issuecomment-5033025087
- Downstream report and traceback: https://github.com/hwdsl2/docker-whisper-live/issues/1
- `websockets` sync server API: https://websockets.readthedocs.io/en/stable/reference/sync/server.html

### PR DESCRIPTION
**Pull request by nightcityblade**
Fixes #532

## Summary

- update the authentication callback to consume `ServerConnection` and `Request`
- return the sync server's response object for unauthorized handshakes
- exercise the production callback with real `Request` objects for header and query authentication

## Testing

- `python -m unittest tests.test_server_extended` (54 tests passed)
- `python -m flake8 tests/test_server_extended.py whisper_live/server.py --count --select=E9,F63,F7,F82 --show-source --statistics` (0 errors)

### CODE REVIEW

File: whisper_live/server.py [hunk 1]
```diff
@@ -28,6 +29,19 @@
 
 logging.basicConfig(level=logging.INFO)
 
+
+def _websocket_auth(api_key, connection, request):
+    auth = request.headers.get("Authorization", "")
+    token_param = None
+    if "?" in request.path:
+        from urllib.parse import urlparse, parse_qs
```
Comment (makaveli10) [inline whisper_live/server.py]: nit: import is inside the function body, so it re-runs on every request that hits the query-string branch? Moving it to the top with the other imports is more conventional.

**Review by makaveli10 — APPROVED** [review]

File: whisper_live/server.py (hunk 1 above)
Comment (nightcityblade) [reply whisper_live/server.py]: Moved the URL parsing imports to module scope in 646c046. The focused WebSocket authentication tests (5/5) and the flake8 syntax/undefined-name checks pass. Thanks for the suggestion.
